### ISSUE TITLE
Can't access file resource from network context

### ISSUE THREAD

**Issue by aecollver** [hyperjump-io/json-schema-validator#2]
I'm trying to load a schema from a file:

```
import { get } from "@hyperjump/json-schema/lib";

const schema = await get("file://" + join(__dirname, "mySchema.json"));

```

I expected this to work based on the example in the readme, but I get this error message:

```
{
  "message": "Can't access file resource from network context",
  "stack": [
    "Error: Can't access file resource from network context",
    "    at safeResolveUrl (/var/task/node_modules/@hyperjump/json-schema-core/lib/schema.js:184:11)",
    "    at Object.get (/var/task/node_modules/@hyperjump/json-schema-core/lib/schema.js:135:23)",
    "    at Resource.doMove (/var/src/api/target-resource.ts:113:26)",
    "    at Resource.handle (/var/src/api/target-resource.ts:48:21)",
    "    at Object.handleProxyEvent (/var/src/api/index.ts:11:37)",
    "    at Runtime.handler (/var/src/application.ts:11:12)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

Am I doing something wrong?

**Comment by aecollver** [comment]
This turned out to be my error (not copying the schema to my output directory). It would be nice if the error message more directly pointed to the problem (I briefly looked at the safeResolveUrl code and my initial thought was a bug in the url scheme matching logic and/or not using the library right).

**Comment by jdesrosiers** [comment]
The error is in response to this.

> JSC can fetch schemas from the web or from the file system, but when fetching from the file system, there are limitations for security reasons. If your schema has an identifier with an http scheme (`http://example.com/my-schema`), it's not allowed to reference schemas with a file scheme (file:///path/to/my/schemas/my-schema.json).

I'm looking into it and there seems to bug where this error is firing when it shouldn't. I should have a fix out this afternoon. I'll also look into improving that error message. It's not very helpful without knowing which file was requested and what the context URL is.

Does your schema have an `$id` or `$ref` with an http scheme? Without knowing what your schema looks like (and the limited error messaging), I can't say if you are getting this error for good reason, or because of the bug.

**Comment by jdesrosiers** [comment]
Here's an example of something that should cause that error. Because the `$id` is `http` (network context), it isn't allowed to `$ref` a file.

```json
{
  "$id": "http://example.com/example.schema.json",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "foo": { "$ref": "file:///path/to/my/schemas/example.schema.json" }
  },
  "required": ["foo"]
}
```

**Comment by aecollver** [comment]
Here's an example schema where I see this error (I've omitted the $id):

```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "name": {
      "title": "Target Name",
      "description": "Target names must begin and end with letters, but may contain numbers, hyphen and underscore.",
      "type": "string",
      "pattern": "^[A-Za-z]([\\w\\-]*[A-Za-z])?$"
    }
  },
  "required": [
    "name"
  ]
}
```

I did unsuccessfully try other variations like the $id like in your example and `"$id": "file:///path/to/my/schema.json"`

**Comment by jdesrosiers** [comment]
There are no `$ref`s in that schema, so there shouldn't be any problem. You're schema is fine. You're just hitting the bug.
